### ISSUE TITLE
UI for proxy management

### ISSUE THREAD

**Issue by natesales** [natesales/aarch64#18]
There is now a new API route for managing the dualstack service proxy, `/proxy`. The methods and example JSON bodies are in the [docs](https://console.aarch64.com/#/docs/api), but it would be great to add another page under the "Manage" tab that contains a table of current proxies and a form for creating a new one. The table should have two columns, the left being Label and the right being VM, and the form should be the same but with a dropdown for VM selection.

**Comment by knightss27** [comment]
I will draw up a figma for this so we can get a sense for what we want it to look like and then I can implement it.

**Comment by natesales** [comment]
Sounds good!

**Comment by knightss27** [comment]
Ok there is a basic layout done, feel free to tell me what you think.

**Comment by natesales** [comment]
Looks good to me. We'll just need a way to group VMs by project in case there are duplicate names between different projects.

**Comment by knightss27** [comment]
This is mostly implemented, if not fully? I am going to close this for now, and issues with how the page works can be opened in separate issues.
