### ISSUE TITLE
Various issues with project creation.

### ISSUE THREAD

**Issue by knightss27** [natesales/aarch64#20]
Upon creating a project, three main problems exist:
- The whole sidebar flashes with `undefined` for around half a second.
- The forwarding to the new project page is broken. (forwards to `projects/[object Object]`)
- Active link highlighting in the sidebar doesn't work until you reload the page.

**Comment by natesales** [comment]
Thanks for documenting this, I can confirm I'm seeing the same thing. Luckily, for the beta we're creating the projects and assigning them to users so we have some time to fix this before users would actually be able to create projects themselves.

**Comment by knightss27** [comment]
Well I fixed them all. Closed by 851e074.
