### ISSUE TITLE
Add status (phoned_home boolean) to VM page

### ISSUE THREAD

**Issue by natesales** [natesales/aarch64#4]

**Comment by knightss27** [comment]
Is this the specific VM page? If so I will decide where to put this.

**Comment by natesales** [comment]
Yep, I'm not sure where it would look best so feel free to decide where it should go.

**Comment by knightss27** [comment]
Added in e4a56c2d49d107731507a59a72b9b907578ec782.
![image](https://user-images.githubusercontent.com/52898165/113107167-7487d100-91b8-11eb-8d49-2002761fd909.png)
![image](https://user-images.githubusercontent.com/52898165/113107231-88333780-91b8-11eb-8539-404fcc90b83e.png)
